// Code generated by "stringer -type=GamePhase"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GamePhaseUninitialized-0]
	_ = x[GamePhaseLobby-1]
	_ = x[GamePhaseHero-2]
	_ = x[GamePhaseProcessing-3]
	_ = x[GamePhasePlayback-4]
	_ = x[GamePhaseDone-5]
}

const _GamePhase_name = "GamePhaseUninitializedGamePhaseLobbyGamePhaseHeroGamePhaseProcessingGamePhasePlaybackGamePhaseDone"

var _GamePhase_index = [...]uint8{0, 22, 36, 49, 68, 85, 98}

func (i GamePhase) String() string {
	if i >= GamePhase(len(_GamePhase_index)-1) {
		return "GamePhase(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GamePhase_name[_GamePhase_index[i]:_GamePhase_index[i+1]]
}
