// Code generated by "stringer -type=GamePhase"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GamePhaseUninitialized-0]
	_ = x[GamePhaseLobby-1]
	_ = x[GamePhaseSplitting-2]
	_ = x[GamePhaseHero-3]
	_ = x[GamePhaseJoining-4]
	_ = x[GamePhasePlayback-5]
	_ = x[GamePhaseDone-6]
}

const _GamePhase_name = "GamePhaseUninitializedGamePhaseLobbyGamePhaseSplittingGamePhaseHeroGamePhaseJoiningGamePhasePlaybackGamePhaseDone"

var _GamePhase_index = [...]uint8{0, 22, 36, 54, 67, 83, 100, 113}

func (i GamePhase) String() string {
	if i >= GamePhase(len(_GamePhase_index)-1) {
		return "GamePhase(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GamePhase_name[_GamePhase_index[i]:_GamePhase_index[i+1]]
}
