// Code generated by "stringer -type=MessageType"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MessageTypeInvalid-0]
	_ = x[MessageTypeExpireLobby-1]
	_ = x[MessageTypeExpireHero-2]
	_ = x[MessageTypeExpirePlayback-3]
	_ = x[MessageTypeControllerJoin-4]
	_ = x[MessageTypeJoin-5]
	_ = x[MessageTypeLeave-6]
	_ = x[MessageTypeSubmitPartialTrack-7]
	_ = x[MessageTypeInitialState-8]
	_ = x[MessageTypeBroadcastConnectedPlayer-9]
	_ = x[MessageTypeBroadcastDisconnectedPlayer-10]
	_ = x[MessageTypeAssignment-11]
	_ = x[MessageTypeBroadcastPhase-12]
	_ = x[MessageTypeBroadcastCombinedTrack-13]
	_ = x[MessageTypeRestart-14]
}

const _MessageType_name = "MessageTypeInvalidMessageTypeExpireLobbyMessageTypeExpireHeroMessageTypeExpirePlaybackMessageTypeControllerJoinMessageTypeJoinMessageTypeLeaveMessageTypeSubmitPartialTrackMessageTypeInitialStateMessageTypeBroadcastConnectedPlayerMessageTypeBroadcastDisconnectedPlayerMessageTypeAssignmentMessageTypeBroadcastPhaseMessageTypeBroadcastCombinedTrackMessageTypeRestart"

var _MessageType_index = [...]uint16{0, 18, 40, 61, 86, 111, 126, 142, 171, 194, 229, 267, 288, 313, 346, 364}

func (i MessageType) String() string {
	if i >= MessageType(len(_MessageType_index)-1) {
		return "MessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
