// Code generated by "stringer -type=Phase"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GamePhaseUninitialized-0]
	_ = x[GamePhaseLobby-1]
	_ = x[GamePhaseHero-2]
	_ = x[GamePhaseProcessing-3]
	_ = x[GamePhasePlayback-4]
	_ = x[GamePhaseDone-5]
}

const _Phase_name = "GamePhaseUninitializedGamePhaseLobbyGamePhaseHeroGamePhaseProcessingGamePhasePlaybackGamePhaseDone"

var _Phase_index = [...]uint8{0, 22, 36, 49, 68, 85, 98}

func (i Phase) String() string {
	if i >= Phase(len(_Phase_index)-1) {
		return "Phase(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Phase_name[_Phase_index[i]:_Phase_index[i+1]]
}
