app = "piano-alone"
kill_signal = "SIGINT"
kill_timeout = 15
primary_region = "ord"

[env]
  SQLITE_DATABASE_PATH="/data/performances.db"

[build]
  dockerfile = "Dockerfile"

[[vm]]
  size = "performance-2x"

[[mounts]]
  source = "piano_alone_data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  [http_service.concurrency]
    type = "connections"
    soft_limit = 500
    hard_limit = 1000

