app = "piano-alone"
kill_signal = "SIGINT"
kill_timeout = 15
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[[mounts]]
  source = "piano_alone_data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

