[[task]]
  id = "dev"
  type = "long"
  dependencies = ["generate", "build-wasm"]
  watch = ["**/*.go"]
  cmd = "go run ./cmd/serve"

[[task]]
  id = "build-wasm"
  type = "short"
  watch = ["**/*.go"]
  dependencies = ["generate", "generate-canvas-api-wrapper"]
  cmd = "GOOS=js GOARCH=wasm go build -o website/main.wasm ./midihero"

[[task]]
  id = "generate"
  type = "short"
  cmd = "go generate ./..."

[[task]]
  id = "generate-canvas-api-wrapper"
  type = "short"
  watch = ["generate_canvas_api_wrapper/main.ts", "generate_canvas_api_wrapper/package.json"]
  cmd = """
    cd generate_canvas_api_wrapper
    yarn
    yarn tsc
    node main.js > ../c2d/c2d.go
    go fmt ../c2d/c2d.go
    echo "done building wrapper"
  """
