[[task]]
  id = "dev"
  type = "long"
  dependencies = ["generate", "build-wasm"]
  cmd = "go run ./cmd/serve"

[[task]]
  id = "build-wasm"
  type = "short"
  watch = ["**/*.go"]
  dependencies = ["generate"]
  cmd = "GOOS=js GOARCH=wasm go build -o website/main.wasm ./midihero"

[[task]]
  id = "generate"
  type = "short"
  cmd = "go generate ./..."
