[[task]]
  id = "dev"
  type = "long"
  dependencies = ["generate", "build-wasm"]
  watch = ["**/*.go"]
  cmd = "go run ./cmd/serve"

[[task]]
  id = "test"
  type = "short"
  dependencies = ["generate", "build-wasm"]
  cmd = """
    go test ./...
    go vet ./...
    go run honnef.co/go/tools/cmd/staticcheck ./...
    go run golang.org/x/vuln/cmd/govulncheck ./...
  """

[[task]]
  id = "build-wasm"
  type = "short"
  watch = ["**/*.go"]
  dependencies = ["generate", "generate-canvas-api-wrapper"]
  cmd = "GOOS=js GOARCH=wasm go build -o website/main.wasm ./midihero"

[[task]]
  id = "generate"
  type = "short"
  cmd = "go generate ./..."

[[task]]
  id = "generate-canvas-api-wrapper"
  type = "short"
  watch = ["generate_canvas_api_wrapper/main.ts", "generate_canvas_api_wrapper/package.json"]
  cmd = """
    cd generate_canvas_api_wrapper
    rm dist/*
    yarn
    yarn tsc
    node dist/main.js
    mv out.go ../c2d/c2d_wasm.go
    go fmt ../c2d/c2d_wasm.go
    echo "done building wrapper"
  """
