// Code generated by "stringer -type=pianoState"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[pianoStateAfterInit-0]
	_ = x[pianoStateDuringHideInactiveKeys-1]
	_ = x[pianoStateAfterHideInactiveKeys-2]
	_ = x[pianoStateDuringMorph-3]
	_ = x[pianoStateAfterMorph-4]
}

const _pianoState_name = "pianoStateAfterInitpianoStateDuringHideInactiveKeyspianoStateAfterHideInactiveKeyspianoStateDuringMorphpianoStateAfterMorph"

var _pianoState_index = [...]uint8{0, 19, 51, 82, 103, 123}

func (i pianoState) String() string {
	if i < 0 || i >= pianoState(len(_pianoState_index)-1) {
		return "pianoState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _pianoState_name[_pianoState_index[i]:_pianoState_index[i+1]]
}
